### ISSUE TITLE
Limbo VNC fails when taping outside of visible desktop

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vgmurphy/limbo-android#9]
```
What steps will reproduce the problem?
1. Limbo VNC fails when taping outside of visible desktop
2.
3.

What is the expected output? What do you see instead?
E/AndroidRuntime(18229): FATAL EXCEPTION: main
E/AndroidRuntime(18229): java.lang.IllegalArgumentException: pointerIndex out 
of range
E/AndroidRuntime(18229):        at 
android.view.MotionEvent.nativeGetAxisValue(Native Method)
E/AndroidRuntime(18229):        at 
android.view.MotionEvent.getX(MotionEvent.java:1988)
E/AndroidRuntime(18229):        at 
com.antlersoft.android.bc.ScaleGestureDetector.getRawX(ScaleGestureDetector.java
:262)
E/AndroidRuntime(18229):        at 
com.antlersoft.android.bc.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector
.java:174)
E/AndroidRuntime(18229):        at 
android.androidVNC.AbstractGestureInputHandler.onTouchEvent(AbstractGestureInput
Handler.java:40)
E/AndroidRuntime(18229):        at 
android.androidVNC.VncCanvasActivity$TouchpadInputHandler.onTouchEvent(VncCanvas
Activity.java:457)
E/AndroidRuntime(18229):        at 
android.androidVNC.VncCanvasActivity.onTouchEvent(VncCanvasActivity.java:1032)
E/AndroidRuntime(18229):        at 
android.app.Activity.dispatchTouchEvent(Activity.java:2367)
E/AndroidRuntime(18229):        at 
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneW
indow.java:1860)
E/AndroidRuntime(18229):        at 
android.view.View.dispatchPointerEvent(View.java:5726)
E/AndroidRuntime(18229):        at 
android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2890)
E/AndroidRuntime(18229):        at 
android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2466)
E/AndroidRuntime(18229):        at 
android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:845)
E/AndroidRuntime(18229):        at 
android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2475)
E/AndroidRuntime(18229):        at 
android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18229):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(18229):        at 
android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime(18229):        at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime(18229):        at 
java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(18229):        at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime(18229):        at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime(18229):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  168):   Force finishing activity 
com.max2idea.android.limbo.main/.LimboVNCActivity

Please use labels and text to provide additional information.

```

Original issue reported on code.google.com by `ideal2i...@gmail.com` on 6 Oct 2012 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed with 0.9.4
```

Original comment by `ideal2i...@gmail.com` on 7 Jan 2013 at 12:04
- Changed state: **Done**
